### ISSUE TITLE
在fragment中可以下拉刷新，但是上滑加载失败，SwipeRefreshLayout和-Ultra-Pull-To-Refresh都出现这个问题

### ISSUE THREAD

**Issue by magicdra** [LuckyJayce/MVCHelper#15]

**Comment by LuckyJayce** [comment]
@magicdra 
你检查下你实现的DataSource 的loadmore方法的代码。
看下失败的错误信息，然后调试看下具体报什么错。

**Comment by magicdra** [comment]
@LuckyJayce 我是按照您给的demo写的，应该不是这个问题，没有报错，显示加载失败，点击加载可以加载出来，但是下滑加载的时候加载不出来

**Comment by LuckyJayce** [comment]
@magicdra 你先调试下loadmore的方法，看是否能正常返回数据。而不是直接回复我 “应该不是这个问题”

**Comment by magicdra** [comment]
@LuckyJayce 可以正常返回数据的，但是下拉加载的时候不能够自动加载数据，需要点击加载才能够加载出数据

**Comment by LuckyJayce** [comment]
加我qq直接聊吧，794629068

**Comment by LuckyJayce** [comment]
问题没描述清楚，他的实际问题是
要点击才能加载数据，那么是说加载是没问题
只是滑动列表的时候不能自动加载数据。

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /> 主要是避免网络没开的时候 滑动底部去加载，加载失败，再滑动一下又加载

如果不是加载网络的话，比如加载数据库的数据，可以设置 helper.setNeedCheckNetwork(needCheckNetwork);  这个
就不会去检查网络状态
