### ISSUE TITLE
demo我出了个问题。加载一次后出现不能刷新，网络请求用的OKHTTP,

### ISSUE THREAD

**Issue by DevFengZI** [LuckyJayce/MVCHelper#16]
所有的都是，比如那个volley 。刷新两次。上啦一次，然后就不能拉了。代码还没仔细看是哪里影响的。搞了一天还以为是别的问题。特别是能拉两下...我还以为手势冲突了。

**Comment by LuckyJayce** [comment]
加群549284336 进一步了解具体的问题
