### ISSUE TITLE
gridview显示数据问题

### ISSUE THREAD

**Issue by wfs3006** [LuckyJayce/MVCHelper#17]
使用demo里提供的GridViewWithHeaderAndFooter显示数据，只能显示一行

**Comment by LuckyJayce** [comment]
@wfs3006 
你运行demo，demo的gridview 是正常的吧。
你仔细看下是写错了。
或者你在下面贴出操作 gridview的代码和gridview的adapter 和girdview 布局

**Comment by wfs3006** [comment]
不好意思，是我不小心写错了
