### ISSUE TITLE
初次进入页面只显示“点击加载更多”，用的SwipeRefreshLayout

### ISSUE THREAD

**Issue by Andecy** [LuckyJayce/MVCHelper#19]
要碰一下屏幕才能出现数据

目前只在4.4及其以下的设备上发现这种情况，初步判断是加入了以下Fragment的onBackPressed：

```
    if ((view = getView()) != null) {
        view.setFocusableInTouchMode(true);
        view.requestFocus();
        view.setOnKeyListener(new View.OnKeyListener() {
            @Override
            public boolean onKey(View v, int keyCode, KeyEvent event) {
                if (event.getAction() == KeyEvent.ACTION_UP && keyCode == KeyEvent.KEYCODE_BACK) {
                    onBackPressed();
                    return true;
                }
                return false;
            }
        });
    }
```

**Comment by LuckyJayce** [comment]
你DataAdapter的IsEmpty 这个判断有问题吧

**Comment by Andecy** [comment]
奇怪了，没有强制让我实现isEmpty

**Comment by Andecy** [comment]
@LuckyJayce 你好，我实现了isEmpty功能，返回的就是我的ArrayList的isEmpty，然而还是不行哦

**Comment by Andecy** [comment]
你的那个例子里面的写法，在初始化的时候就把Adapter中的List用new初始化了，服务器返回json空数组[]，就不能显示空数据界面了吧？

**Comment by wfs3006** [comment]
@Andecy 问题解决了吗，我也遇到了，有时候能显示出来数据，有时候需要触摸一下

**Comment by Andecy** [comment]
@wfs3006 你好，请问是否用了Fragment的onBackPressed？

**Comment by wfs3006** [comment]
没有用到

**Comment by Andecy** [comment]
@wfs3006 请问你的系统版本是？

**Comment by wfs3006** [comment]
5.0来自我的华为手机-------- 原始邮件 --------主题：Re: [LuckyJayce/MVCHelper] 初次进入页面只显示“点击加载更多”，用的SwipeRefreshLayout (#19)发件人：Andecy 收件人：LuckyJayce/MVCHelper 抄送：wangfusheng @wfs3006 请问你的系统版本是？

**Comment by Andecy** [comment]
@wfs3006 你有在代码中调用setFocusableInTouchMode这个代码不？

**Comment by wfs3006** [comment]
没有调用

**Comment by Andecy** [comment]
@wfs3006 那我也不是很清楚了T_T

**Comment by wfs3006** [comment]
@Andecy 嗯期待作者回复

**Comment by LuckyJayce** [comment]
1.建议使用 SwipeRefreshLayout + RecyclerView。

之前的原因是界面上有代码改变焦点， SwipeRefreshLayout被切换loading布局，然后显示数据的时候切换回SwipeRefreshLayout，listview适配器虽然已经notify但是listview界面不更新。而测试RecyclerView是ok

2.或者可以LoadView的布局切换使用VaryViewHelperXV

（用于切换布局,用一个新的布局覆盖在原布局之上,原先的布局被切换时候就被掩藏，restoreView时显示），避免SwipeRefreshLayout的切换问题

**Comment by Andecy** [comment]
@wfs3006 作者回复了~

问题得到解决，谢谢！

**Comment by sunlimiter** [comment]
不行哎，初始化数据调refresh()会默认执行RefreshAsyncTask 下 mLoadMoreView.showNormal(); 这句showNormal里面默认又会显示“点击加载更多”，现在只好在showNormal这个方法里把那句置空掉。。。
