### ISSUE TITLE
请问只能通过Data2和Data3设定一些让用户调整的参数吗？

### ISSUE THREAD

**Issue by Andecy** [LuckyJayce/MVCHelper#20]
比如我这个列表页带有让用户搜索、筛选的条件，比如有三四个，那么有什么好的方法推荐呢？

**Comment by LuckyJayce** [comment]
你是说DataSource<Data>的泛型吧，这是Model获取数据的类型，你可以定义实体类，也可以用Data3这种简单的表示。返回的数据有很多的字段的话，还是建议定义实体类
该框架有什么问题的话可以加群直接提问，群号：549284336

**Comment by Andecy** [comment]
呃，我可能表达和理解错了，是这样，就是用户可能在同一个页面会改变请求参数，比如搜索/筛选什么的
