### ISSUE TITLE
在Fragment中实现onBackPressed导致第一次数据无法显示

### ISSUE THREAD

**Issue by Andecy** [LuckyJayce/MVCHelper#21]
采用的是下面这种方法来返回：

http://stackoverflow.com/questions/5448653/how-to-implement-onbackpressed-in-android-fragments

导致要点一下才能出来数据

**Comment by Andecy** [comment]
试了下普通的Adapter是可以的。。。希望能指点一下思路。。

**Comment by LuckyJayce** [comment]
1.建议使用 SwipeRefreshLayout + RecyclerView。

之前的原因是界面上有输入框， SwipeRefreshLayout被切换loading布局，然后显示数据的时候切换回SwipeRefreshLayout，listview适配器虽然已经notify但是listview界面不更新。而测试RecyclerView是ok

2.或者可以LoadView的布局切换使用VaryViewHelperXV

（用于切换布局,用一个新的布局覆盖在原布局之上,原先的布局被切换时候就被掩藏，restoreView时显示），避免SwipeRefreshLayout的切换问题
