### ISSUE TITLE
listview显示数据问题

### ISSUE THREAD

**Issue by wfs3006** [LuckyJayce/MVCHelper#22]
viewpager嵌套的fragment中使用listview加载数据，有时候只显示一个footer《已经加载完毕》或《点击加载更多》，手动刷新一下数据才能显示，不知道为什么，请教作者，用的SwipeRefreshLayout内嵌listview

**Comment by LuckyJayce** [comment]
1.建议使用 SwipeRefreshLayout + RecyclerView。

之前的原因是界面上有输入框， SwipeRefreshLayout被切换loading布局，然后显示数据的时候切换回SwipeRefreshLayout，listview适配器虽然已经notify但是listview界面不更新。而测试RecyclerView是ok

2.或者可以LoadView的布局切换使用VaryViewHelperXV

（用于切换布局,用一个新的布局覆盖在原布局之上,原先的布局被切换时候就被掩藏，restoreView时显示），避免SwipeRefreshLayout的切换问题

**Comment by wfs3006** [comment]
嗯，好的，感谢楼主
