### ISSUE TITLE
你该更新jar包了，坑爹啊 0.0

### ISSUE THREAD

**Issue by arnohxr** [LuckyJayce/MVCHelper#23]
使用jar包的话，SwipeRefreshLayout 结合 recyclerview会出现问题，‘点击加载更多’即loadmoreview会占据一整页屏幕添加到reyclerview底部。但是使用依赖工程MVCHelper_Library就不会出现问题。我eclipse用依赖工程运行没问题，studio运行jar包就出现问题，一模一样的代码，害得我蛋疼了几天，刚才发现可能是jar包跟MVCHelper_Library版本不一样，于是把eclipse工程也换成jar包，果然就出现了同样的问题...

**Comment by LuckyJayce** [comment]
已经更新
