### ISSUE TITLE
用android-Ultra-Pull-To-Refresh-library做刷新框架，出现的问题

### ISSUE THREAD

**Issue by blueskyfred1** [LuckyJayce/MVCHelper#27]
用android-Ultra-Pull-To-Refresh-library做刷新框架，比照demo来做，代码都是拷贝过来的，运行的时候可以下拉刷新，也可以按照分页加载更多，但是就是不显示listview，head下面紧跟着“点击加载更多”，没有listview，不知道哪里出问题了

**Comment by blueskyfred1** [comment]
我怀疑demo里的代码，根本没有把xml布局文件里的listview写到代码里，因为全局搜索listview的id,只在xml里有用到

**Comment by blueskyfred1** [comment]
如果我用到listview里item的点击事件，我该怎么用呢

**Comment by blueskyfred1** [comment]
@Override
    public int getCount() {
        Log.i("zk","count:"+books.size());
        return books.size();
    }

 @Override
    public void notifyDataChanged(List<Book> books, boolean isRefresh) {
        Log.i("zk","执行了");
        Log.i("zk","books:"+books.size());
        if (isRefresh) {
            books.clear();
        }
        books.addAll(books);
        notifyDataSetChanged();
 }
getcount（）返回0，不清楚为什么

**Comment by LuckyJayce** [comment]
ListView的点击事件还是使用原来的方法设置
books.addAll(books);
自己添加自己，你写错了
