### ISSUE TITLE
SwipeRefreshLayout + RecyclerView, item点击事件异常

### ISSUE THREAD

**Issue by jackzhonglyy** [LuckyJayce/MVCHelper#28]
项目环境：SwipeRefreshLayout + RecyclerView + CommonAdapter
bug描述：使用了Mvchelper的recyclerview中有一个item，item中有一个button，此时分别为item root布局和button添加点击时间，root点击11:56:49不会触发。如果不适用Mvchlper则root时间触发。

**Comment by LuckyJayce** [comment]
@jackzhonglyy 是因为我用代理的adapter（设置一层代理的adapter用于header和footer）里面有设置点击事件，你的setRoot的点击事件被我覆盖，你qq多少，我发个去掉点击事件的代理adapter修改好的给你试下
