### ISSUE TITLE
第一次加载数据的时候不显示数据，点击重试按钮后得到数据。

### ISSUE THREAD

**Issue by elriczhan** [LuckyJayce/MVCHelper#32]
用的是MVCNormalHelper参数是 recyclerView 返回的数据是一个Bean而不是List，第一次加载数据就会不显示，偶尔会显示。

**Comment by LuckyJayce** [comment]
@elriczhan  datasource 打印一下有没请求成功
你在adapter的 notifydatachange打印一下 看下有没有调用

**Comment by elriczhan** [comment]
嗯 我测试了， 请求成功了，notifydatachange 也打印了。

**Comment by LuckyJayce** [comment]
那应该显示列表界面了啊，怎么还有重试按钮

**Comment by elriczhan** [comment]
不清楚是为什么，偶尔会显示出数据，但是大部分情况都是出现 重试 按钮

**Comment by elriczhan** [comment]
第一次onCompleted 打印了， 然后没有notifydatachange， 点击 重试的时候onCompleted中打印了 ，notify也打印了。 问题应该是没有调用notify， 这是什么原因呢

**Comment by LuckyJayce** [comment]
数据成功还显示重试按钮?
你会不会有多次请求，前面成功后面失败
datasource贴出来看下

**Comment by elriczhan** [comment]
public class PredictionDataSource implements IDataSource\<PredictionBean\> {
    private PredictionBean prediction;

    @Override
    public PredictionBean refresh() throws Exception {
        return loadData();
    }

    private PredictionBean loadData() {
        App.retrofitInstance().create(PredictionDataSource.ILoadBigvs.class).getPrediction("json")     //获取Observable对象
                .observeOn(AndroidSchedulers.mainThread())//最后在主线程中执行
                .subscribe(new Subscriber<PredictionBean>() {

                    @Override
                    public void onCompleted() {
                        System.out.println("request compelete =========");
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.e(getClass().getName(), e.toString());
                        System.out.println(" ========errror happen=====");
                    }

                    @Override
                    public void onNext(PredictionBean predictionBean) {
                        prediction = predictionBean;
                        System.out.println("on next ------------");
                    }
                });

        System.out.println("load data finish========");
        return prediction;
    }

    @Override
    public PredictionBean loadMore() throws Exception {
        return null;
    }

    @Override
    public boolean hasMore() {
        return false;
    }


    interface ILoadBigvs {
        @GET(HttpUrls.PREDICTION)
        Observable<PredictionBean> getPrediction(
                @Query("format") String format
        );
    }
}

**Comment by LuckyJayce** [comment]
你这是异步的要用iasyncdatasource
同步请求直接返回结果的才用datasource

**Comment by elriczhan** [comment]
请问有异步的demo吗

**Comment by LuckyJayce** [comment]
demo中也有rxjava的例子啊，好好看下
