### ISSUE TITLE
这个非常好用，但有个问题

### ISSUE THREAD

**Issue by bestfc** [LuckyJayce/MVCHelper#33]
第一个问题，是你的群的入口问题，确实不知道怎么回事，嗯，java是新手
第二个问题，是想进群问的问题。。。
mvcHelper.getDataSource()得到的是同步datasource，异步的没有？反正我这是得到null

**Comment by LuckyJayce** [comment]
确实没提供一个返回异步的datasource，目前你要用的话需要你自己保存datasource
群的问题只是个简单程序员计算题，确定加群的是程序员

**Comment by bestfc** [comment]
好的，我确实是重新setDataSource，就可以了
这个计算题我确实不懂，我这是半路出家的码农
