### ISSUE TITLE
空布局显示问题

### ISSUE THREAD

**Issue by duwurensheng010** [LuckyJayce/MVCHelper#39]
多个item时，挨个删除直至全部删除后，空布局不会自动显示
![image](https://cloud.githubusercontent.com/assets/7730269/25799422/77ef1d88-3417-11e7-912f-9f89333db90f.png)

**Comment by LuckyJayce** [comment]
手动删除item，你可以自己判断，
为空的时候 mvchelper.getLoadView().showEmpty();
没地方注册删除的监听啊，总不可能在adapter注册，那耦合太严重

**Comment by duwurensheng010** [comment]
嗯，也是，谢谢！
