### ISSUE TITLE
请问怎么和android-async-http配合使用

### ISSUE THREAD

**Issue by simdm** [LuckyJayce/MVCHelper#4]
我使用android-async-http来处理网络请求，但android-async-http使用的都是回调的方式返回结果，
例如：

class TwitterRestClientUsage {
    public void getPublicTimeline() throws JSONException {
        TwitterRestClient.get("statuses/public_timeline.json", null, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                // If the response is JSONObject instead of expected JSONArray
            }

```
        @Override
        public void onSuccess(int statusCode, Header[] headers, JSONArray timeline) {
            // Pull out the first event on the public timeline
            JSONObject firstEvent = timeline.get(0);
            String tweetText = firstEvent.getString("text");

            // Do something with the response
            System.out.println(tweetText);
        }
    });
}
```

}

而您提供的数据访问接口里是同步请求，请问我怎么才能把android-async-http的访问封装进去，谢谢。

```
private List<Book> loadBooks(int page) throws Exception {
    // 这里用百度首页模拟网络请求，如果网路出错的话，直接抛异常不会执行后面的获取books的语句
    HttpUtils.executeGet("http://www.baidu.com");
    Thread.sleep(300);

    List<Book> books = new ArrayList<Book>();
    for (int i = 0; i < 20; i++) {
        books.add(new Book("page" + page + "  Java编程思想 " + i, 108.00d));
    }
    this.page = page;
    return books;
}
```

**Comment by LuckyJayce** [comment]
用 private static SyncHttpClient httpClient = new SyncHttpClient();这个

**Comment by simdm** [comment]
thanks

**Comment by LuckyJayce** [comment]
@simdm 已经添加IAsyncDataSource 具体例子查看 VolleyGridViewActivity 和 BooksAsyncDataSource
同样也适用于android-async-http

**Comment by simdm** [comment]
谢谢
