### ISSUE TITLE
怎样配合vlayout一起使用？

### ISSUE THREAD

**Issue by yihuajia** [LuckyJayce/MVCHelper#41]
你好，尝试过配合vlayout一起使用，但是在layoutManager及adapter设置上有冲突

**Comment by LuckyJayce** [comment]
1. setAdapter(IDataAdapter<DATA> adapter)  
adapter继承RecyclerView.Adapter 实现IDataAdapter接口
2. setAdapter2(Object viewAdapter, IDataAdapter<DATA> dataAdapter)
viewAdapter 继承RecyclerView.Adapter，dataAdapter实现IDataAdapter接口

如果第一种不容易用，那也可以用第二种

**Comment by yihuajia** [comment]
好的谢谢，感觉这两种好像 都没有什么区别啊。。我先试试吧
