### ISSUE TITLE
结合vlayout使用

### ISSUE THREAD

**Issue by yihuajia** [LuckyJayce/MVCHelper#46]
你好，请问在结合vlayout使用，在加载更多的时候，底部那个加载更多提示 就只能是自己再去实现了？

**Comment by LuckyJayce** [comment]
不用，你用MVCHelper设置vlayout 的adapter就好了，MVCHelper里面会通过HFRecyclerAdapter 设置一个代理类去添加Footer

**Comment by yihuajia** [comment]
那就是说vlayout的DelegateAdapter得去实现IDataAdapter这个接口了，然后再把返回的数据设置进DelegateAdapter中的一个adapter?

**Comment by LuckyJayce** [comment]
实现IDataAdapter接口的方法就可以了

**Comment by LuckyJayce** [comment]
数据是有MVCHelper通过执行IDataSource
然后调用IDataAdapter的notifyDataChange把数据传给IDataAdapter

**Comment by yihuajia** [comment]
明白，，我试试。。谢谢哈
