### ISSUE TITLE
不能带缓存吗 ？一断网 数据全没有了

### ISSUE THREAD

**Issue by IndexOutOfBounds998** [LuckyJayce/MVCHelper#49]

**Comment by LuckyJayce** [comment]
缓存逻辑要自己写，这功能不属于该类库

**Comment by IndexOutOfBounds998** [comment]
哦哦 行吧

**Comment by IndexOutOfBounds998** [comment]
老哥 断网的时候  上拉界面 第一次加载了loadDatas  翻到第二页的时候不加载了 这个是什么情况

**Comment by LuckyJayce** [comment]
你调试看下datasource的loadmore和hasmore有没加载

**Comment by IndexOutOfBounds998** [comment]
第一次加载 拉倒底部 不加载了 hasMore 返回的是true

**Comment by IndexOutOfBounds998** [comment]
因为默认是滑动到底部 检查是否有网络，没网络就不需要触发加载更多的操作。 mvcHelper.setNeedCheckNetwork(boolean needCheckNetwork) needCheckNetwork设置为false就不检查网络。 哈哈哈 解决了
