### ISSUE TITLE
DataSource中refresh（）方法如何实现异步加载？

### ISSUE THREAD

**Issue by ganghuaChen** [LuckyJayce/MVCHelper#5]
假如DataSource的refresh（）方法与Volley结合获取网络数据，如何实现呢。

**Comment by LuckyJayce** [comment]
private static BasicNetwork network = new BasicNetwork(new HurlStack());
....
NetworkResponse networkResponse = network .performRequest(request);

**Comment by LuckyJayce** [comment]
建议还是用其他有同步执行的框架来结合该类库，比如OkHttp

**Comment by ganghuaChen** [comment]
3Q.不过这样是否会破坏了volley的完整性呢？ 能否在MVCHelper中加入异步处理的实现。

**Comment by LuckyJayce** [comment]
MVCHelper 加入异步处理 这个需求也是可以的，不过最近有些忙，没那么快加入

**Comment by ganghuaChen** [comment]
好的，谢谢。

**Comment by LuckyJayce** [comment]
@ganghuaChen 已经添加IAsyncDataSource 具体例子查看 VolleyGridViewActivity 和 BooksAsyncDataSource

**Comment by ganghuaChen** [comment]
感谢，还准备自己去改的！
