### ISSUE TITLE
建议采用Gradle来构建项目

### ISSUE THREAD

**Issue by junbinchencn** [LuckyJayce/MVCHelper#8]
可以直接用Android Studio 来编译项目，不用做大量处理

**Comment by w4mxl** [comment]
同样希望能把 library 做成 gradle 依赖的方式，这样会很大程度上加快我们集成这个工具的速度

**Comment by steventong** [comment]
+1

**Comment by fraborna** [comment]
+1

**Comment by Sanjay-F** [comment]
+2

**Comment by Lujango** [comment]
+3

**Comment by NicodeLee** [comment]
把项目迁移到Android Studio的一个版本：https://github.com/NicodeLee/MVCHelper

**Comment by cikichen** [comment]
+1

**Comment by zeQq** [comment]
+1

**Comment by ruanruandc** [comment]
+1

**Comment by liyanlei666** [comment]
+1

**Comment by qigithub** [comment]
+1

**Comment by LuckyJayce** [comment]
@junbinchencn @w4mxl @steventong @fraborna @Sanjay-F @NicodeLee @Lujango @cikichen
@zeQq @weiyi308 @liyanlei666 @qigithub
终于提交到了jcenter上面了，终于可以关闭这个issues了。
尽情的使用吧。^_^
